version: "3.8"

services:
  app:
    build: .
    container_name: lumen-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:yuozoXl6nMxItg2LEJDifU4hmNxlIg/q47oQ30s/F4E=
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: dbh # Database name
      DB_USERNAME: root
      DB_PASSWORD: secret
    depends_on:
      - db

  db:
    image: mysql/mysql-server:5.7
    container_name: lumen-db
    restart: always
    environment:
      MYSQL_DATABASE: dbh
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
